### ISSUE TITLE
Detaillierte Informationen über eine Haltestelle

### ISSUE THREAD

**Issue by fafengut** [fafengut/vbb-stop-service#4]
## Feature

Als Nutzer:in möchte ich auf eine Haltestelle klicken können mit dem Ziel detaillierte Informationen zu dieser Haltestelle und den Abfahrten zu erhalten. Falls die Informationen nicht angezeigt werden können, dann möchte ich darüber informiert werden und auf der Übersichtsseite bleiben.

## Tasks

- [x] Seite mit Detailinformationen erstellen
- [x] Informationen über die API befüllen
- [x] Auflistung der Abfahrten hinzufügen
- [x] Routing zu den einzelnen Seiten implementieren
