### ISSUE TITLE
Haltestellen favorisieren

### ISSUE THREAD

**Issue by fafengut** [fafengut/vbb-stop-service#5]
## Feature

Als Nutzer:in möchte ich einzelne Haltstellen als Favoriten speichern mit dem Ziel eine Auflistung von favorisierten Haltestellen zu haben. Falls das Favorisieren einer Haltestelle nicht möglich ist, dann möchte ich eine Fehlermeldung erhalten.

## Tasks

- [x] Button zum Hinzufügen zu den Favoriten auf der Übersichtsseite und detaillierten Seite ergänzen
- [x] Informationen zum Localstorage hinzufügen ( Lösung ohne Authentifizierung und DB )
- [x] Neuen Reiter/Bereich erstellen, um alle Favoriten aufzulisten
